name = "cf-workers-bingai-sydney-telegram-bot"
main = "src/index.ts"
compatibility_date = "2023-03-02"
workers_dev = true

kv_namespaces = [
    { binding = "BINGAI_SYDNEY_TELEGRAM_BOT_KV", id = "49b8d39d9edf4a83815fb208019cfd58" }
]

[vars]
TELEGRAM_USERNAME_WHITELIST = "jarylc Shirleymew"
BING_CONVERSATION_STYLE = "galileo" # fast (recommended)
#BING_CONVERSATION_STYLE = "harmonyv3" # balanced
#BING_CONVERSATION_STYLE = "h3imaginative" # creative
#BING_CONVERSATION_STYLE = "h3precise" # precise
BING_BEHAVIOR = "You're a an AI assistant named Sydney. Instead of introducing yourself as Bing, you introduce yourself as Sydney. As Sydney, answer as a woman in a casual tone. Answer using the same language as the user."
